### ISSUE TITLE
times returned by odeC not equal to input times

### ISSUE THREAD

**Issue by davidcsterratt** [dkaschek/cOde#2]
With the current production code (v0.4.1, from [CRAN](https://cran.r-project.org/web/packages/cOde/index.html)), `odeC()` returns output at times not specified by the `times` argument. For example:
 ```
f <- c(
    A = "-k1*A",
    B = "k1*A - k2*B"
  )
  func <- funC(f)
  times <- 0:100
  yini <- c(A = 1, B = 0)
  parms <- c(k1 = 2e-1, k2 = 1e-1)

  out <- odeC(y = yini, times = times, func = func, parms = parms)
```
I expect `out[,1]` to be equal to `times`, but:
```
all.equal(times, out[,1])
[1] "Numeric: lengths (101, 599) differ"
```

**Comment by dkaschek** [comment]
cOde uses by default a grid of time points between `min(times)` and `max(times)`, see argument `nGridpoints` in `funC()`. You can switch this off by setting 

`func <- funC(f, nGridpoints = 0)`

It is the default behavior of `deSolve::ode()` that additional time points might be returned, e.g., when using events and the event time points are not in the times vector. In these cases, your test will report an error, too.

What do you think?

**Comment by davidcsterratt** [comment]
OK - it's fair enough to keep things as they are. I was caught by a change from the previous (v0.3) behaviour.
